services:
  app:
    container_name: go-echo-boilerplate-api
    hostname: backend
    image: go-echo-boilerplate:latest
    build:
      context: .
      dockerfile: builds/Dockerfile
      tags:
      - go-echo-boilerplate:latest
    environment:
      - ENV=dev
    volumes:
      - ./config/config.dev.yaml:/config/config.dev.yaml
    ports:
      - 8090:8080
  postgres:
    container_name: go-echo-boilerplate-db
    hostname: pgdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5888:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
    driver: local